name: ThaiRoCorePlugin
version: '0.1.0-SNAPSHOT'
main: org.rostats.ThaiRoCorePlugin
api-version: '1.21'
loader: PAPER
author: YourName

# Dependencies Configuration for Paper 1.21+
dependencies:
  server:
    ProtocolLib:
      load: BEFORE
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: true
      join-classpath: true
    MythicMobs: # Changed from Mythic-Dist to match actual plugin name
      load: BEFORE
      required: true
      join-classpath: true

# Commands
commands:
  status:
    description: Open player status menu
    usage: /status
    aliases: [st, char]
  roadmin:
    description: Admin commands for ROStats
    usage: /roadmin <args>
    permission: rostats.admin
  roitemedit:
    description: Open the Item Attribute Editor GUI
    usage: /roitemedit
    aliases: [riedit]
    permission: rostats.itemeditor.admin
  roskilleditor:
    description: Skill creation and management menu
    usage: /roskilleditor
    permission: rostats.admin

# Permissions
permissions:
  rostats.admin:
    description: Admin permission
    default: op
  rostats.itemeditor.admin:
    description: Permission to use the Item Attribute Editor
    default: op