name: ThaiRoCorePlugin # RENAMED
version: '0.1.0-SNAPSHOT'
main: org.rostats.ThaiRoCorePlugin # RENAMED
api-version: '1.21'
commands:
  status:
    description: Open player status menu
    usage: /status
    aliases: [st, char]
  roadmin:
    description: Admin commands for ROStats
    usage: /roadmin <args>
    permission: rostats.admin
  roitemedit: # ADDED from Item Editor Plugin
    description: Open the Item Attribute Editor GUI
    usage: /roitemedit
    aliases: [riedit]
    permission: rostats.itemeditor.admin
permissions:
  rostats.admin:
    description: Admin permission
    default: op
  rostats.itemeditor.admin: # ADDED from Item Editor Plugin
    description: Permission to use the Item Attribute Editor
    default: op